Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Bookshelf.Models;
namespace Bookshelf.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Components/CategoriesViewComponent.cs
using Bookshelf.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bookshelf.Components
{
    public class CategoriesViewComponent : ViewComponent
    {
        private IBookstoreRepository repo { get; set; }

        public CategoriesViewComponent (IBookstoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            // I'm not sure what this ["Category"] is referring to ... 
            ViewBag.SelectedCategory = RouteData?.Values["bookCategory"];

            var categories = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(categories);
        }
    }
}

Views/Shared/BookSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Book

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h3>@Model.Title</h3>
    </div>
    <div class="card-text p-1">
        <ul>
            <li>Book ID: @Model.BookId</li>
            <li>Author: @Model.Author</li>
            <li>Publisher: @Model.Publisher</li>
            <li>ISBN: @Model.Isbn</li>
            <li>Classification: @Model.Classification</li>
            <li>Category: @Model.Category</li>
            <li>Page Count: @Model.PageCount pages</li>
            <li>Price: $@Model.Price</li>
        </ul>

        <form method="post" asp-page="/Cart">
            <input type="hidden" asp-for="@Model.BookId" />
            <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
            <span class="card-text">
                <button type="submit" class="btn btn-success btn-sm float-end">Add to Cart</button>
            </span>
        </form>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />

</head>
<body>

    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">BookStore</div>
                <div class="col-6 text-right">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>

    <div class="row m-1 p-1">

        <div id="types" class="col-3">
            <vc:categories></vc:categories>
        </div>

        <div class="col-9">
            <div>
                @RenderBody()
            </div>
        </div>

    </div>
</body>
</html>